### ISSUE TITLE
Error using mksqlite unrecognized token: " "

### ISSUE THREAD

**Issue by KlaymenGC** [AndreasMartin72/mksqlite#4]
Hello,

Thanks for this great mex. I've got some trouble in running the SQLite lines in MATLAB, here is the code:

```
idx = 1;
mksqlite( 'begin' );
mksqlite( ['INSERT INTO ', table , ...
             ' (Data_ID, Value) ', ... % Data_ID: INTEGER, Value: TEXT
             '  VALUES(' idx, ', readfile(' idx, '.txt))'] );
mksqlite( 'commit' );
```

it always gave me: 

```
Error using mksqlite
unrecognized token: " "
```

I think the SQL lines have no problem, but I don't know why it keeps giving me the error, any ideas? @AndreasMartin72 
Thanks in advance!

**Comment by a-ma72** [comment]
Hello,

at least there seems 'idx' to be passed wrongly, since you concat a string with an integer?
Please take a look at your SQL statement firstly by parsing it: Select only the brace '[...]' with contents and parse it by pressing F9. Look if that is the SQL statement you expect...

Regards, Andreas
